# Generated by Django 4.1 on 2022-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railbase', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
